name: example
description: Usage example and test pad.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.0.0
  equatable: ^2.0.5
  cupertino_icons: ^1.0.5

  divkit:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/application/
    - assets/application/images/
    - assets/test_data/expression_test_data/
    - assets/test_data/samples/animations/
    - assets/test_data/samples/base/
    - assets/test_data/samples/container/
    - assets/test_data/samples/gallery/
    - assets/test_data/samples/grid/
    - assets/test_data/samples/image/
    - assets/test_data/samples/input/
    - assets/test_data/samples/pager/
    - assets/test_data/samples/select/
    - assets/test_data/samples/separator/
    - assets/test_data/samples/slider/
    - assets/test_data/samples/state/
    - assets/test_data/samples/tabs/
    - assets/test_data/samples/text/
    - assets/test_data/samples/video/
    - assets/test_data/regression_test_data/
    - assets/test_data/regression_test_data/accessibility/
    - assets/test_data/regression_test_data/accessibility/mode/
    - assets/test_data/regression_test_data/action_animation/
    - assets/test_data/regression_test_data/animations/
    - assets/test_data/regression_test_data/animations/lottie/
    - assets/test_data/regression_test_data/animations/transition/
    - assets/test_data/regression_test_data/animations/rive/
    - assets/test_data/regression_test_data/gallery/
    - assets/test_data/regression_test_data/pager/
    - assets/test_data/regression_test_data/variables/
    - assets/test_data/regression_test_data/video/
    - assets/test_data/regression_test_data/actions/
    - assets/test_data/regression_test_data/container/
    - assets/test_data/regression_test_data/patch/
    - assets/test_data/regression_test_data/rebind/
    - assets/test_data/regression_test_data/rebind/gallery/
    - assets/test_data/regression_test_data/rebind/grid/
    - assets/test_data/regression_test_data/rebind/pager/
    - assets/test_data/regression_test_data/rebind/tabs/
    - assets/test_data/regression_test_data/state/
    - assets/test_data/regression_test_data/timers/
    - assets/test_data/regression_test_data/visibility_actions/
