[versions]
agp = "8.13.2"
compose = "1.10.0"
divkit = "32.34.0"
kotlin = "2.3.0"
material3 = "1.9.0"


[libraries]
androidx-activityCompose = { module = "androidx.activity:activity-compose", version = "1.12.2" }

div = { module = "com.yandex.div:div", version.ref = "divkit" }
div-core = { module = "com.yandex.div:div-core", version.ref = "divkit" }
div-glide = { module = "com.yandex.div:glide", version.ref = "divkit" }
div-picasso = { module = "com.yandex.div:picasso", version.ref = "divkit" }
div-shimmer = { module = "com.yandex.div:div-shimmer", version.ref = "divkit" }

foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
nexusPublish = { module = "io.github.gradle-nexus:publish-plugin", version = "2.0.0" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
